import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "@/providers";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PhoneShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={recursive.className}>
          <main className="flex grainy-light  flex-col min-h-[calc(100vh-3.5rem-1px)]">
            <div className="flex-1 flex flex-col h-full ">
              <Providers>{children}</Providers>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
