import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import Providers from '@/components/Providers';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { UserProvider } from "@auth0/nextjs-auth0/client";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PhoneShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={recursive.className}>
          <Providers>
            <Navbar />
            <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
              <div className="flex-1 flex flex-col h-full">{children}</div>
              <Footer />
            </main>
          </Providers>
        </body>
      </UserProvider>
    </html>
  );
}
